export const statements: string[] = [
  "CREATE TYPE \"public\".\"enum_users_role\" AS ENUM('admin', 'staff');",
  "CREATE TYPE \"public\".\"enum_product_categories_icon\" AS ENUM('beef', 'milk', 'beer', 'wheat', 'egg', 'honey', 'cheese', 'wine', 'carrot', 'apple', 'shopping-bag');",
  "CREATE TYPE \"public\".\"enum_product_categories_color\" AS ENUM('groen', 'paars', 'oranje', 'blauw', 'creme');",
  "CREATE TYPE \"public\".\"enum_products_unit\" AS ENUM('stuk', 'pakje', 'fles', 'kg', '100g', 'liter', 'zes', 'twaalf');",
  "CREATE TYPE \"public\".\"enum_bread_items_category\" AS ENUM('broodje-zacht', 'broodje-hard', 'croissant', 'eieren', 'anders');",
  "CREATE TYPE \"public\".\"enum_bookings_status\" AS ENUM('active', 'upcoming', 'closed', 'cancelled');",
  "CREATE TYPE \"public\".\"enum_bookings_external_source\" AS ENUM('manual', 'uwboeking', 'website');",
  "CREATE TYPE \"public\".\"enum_orders_type\" AS ENUM('shop', 'bread');",
  "CREATE TYPE \"public\".\"enum_orders_guest_type\" AS ENUM('camper', 'passant');",
  "CREATE TYPE \"public\".\"enum_orders_payment_method\" AS ENUM('mollie', 'tab');",
  "CREATE TYPE \"public\".\"enum_orders_payment_status\" AS ENUM('open', 'paid', 'tab', 'failed', 'cancelled');",
  "CREATE TABLE \"users_sessions\" (\n\t\"_order\" integer NOT NULL,\n\t\"_parent_id\" integer NOT NULL,\n\t\"id\" varchar PRIMARY KEY NOT NULL,\n\t\"created_at\" timestamp(3) with time zone,\n\t\"expires_at\" timestamp(3) with time zone NOT NULL\n);\n",
  "CREATE TABLE \"users\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" varchar NOT NULL,\n\t\"role\" \"enum_users_role\" DEFAULT 'admin' NOT NULL,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"email\" varchar NOT NULL,\n\t\"reset_password_token\" varchar,\n\t\"reset_password_expiration\" timestamp(3) with time zone,\n\t\"salt\" varchar,\n\t\"hash\" varchar,\n\t\"login_attempts\" numeric DEFAULT 0,\n\t\"lock_until\" timestamp(3) with time zone\n);\n",
  "CREATE TABLE \"media\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"alt\" varchar NOT NULL,\n\t\"caption\" varchar,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"url\" varchar,\n\t\"thumbnail_u_r_l\" varchar,\n\t\"filename\" varchar,\n\t\"mime_type\" varchar,\n\t\"filesize\" numeric,\n\t\"width\" numeric,\n\t\"height\" numeric,\n\t\"focal_x\" numeric,\n\t\"focal_y\" numeric,\n\t\"sizes_thumbnail_url\" varchar,\n\t\"sizes_thumbnail_width\" numeric,\n\t\"sizes_thumbnail_height\" numeric,\n\t\"sizes_thumbnail_mime_type\" varchar,\n\t\"sizes_thumbnail_filesize\" numeric,\n\t\"sizes_thumbnail_filename\" varchar,\n\t\"sizes_card_url\" varchar,\n\t\"sizes_card_width\" numeric,\n\t\"sizes_card_height\" numeric,\n\t\"sizes_card_mime_type\" varchar,\n\t\"sizes_card_filesize\" numeric,\n\t\"sizes_card_filename\" varchar,\n\t\"sizes_hero_url\" varchar,\n\t\"sizes_hero_width\" numeric,\n\t\"sizes_hero_height\" numeric,\n\t\"sizes_hero_mime_type\" varchar,\n\t\"sizes_hero_filesize\" numeric,\n\t\"sizes_hero_filename\" varchar\n);\n",
  "CREATE TABLE \"product_categories\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" varchar NOT NULL,\n\t\"slug\" varchar NOT NULL,\n\t\"description\" varchar,\n\t\"icon\" \"enum_product_categories_icon\" DEFAULT 'shopping-bag',\n\t\"color\" \"enum_product_categories_color\" DEFAULT 'groen',\n\t\"image_id\" integer,\n\t\"order\" numeric DEFAULT 100,\n\t\"active\" boolean DEFAULT true,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"products\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" varchar NOT NULL,\n\t\"slug\" varchar NOT NULL,\n\t\"category_id\" integer NOT NULL,\n\t\"description\" varchar,\n\t\"image_id\" integer,\n\t\"price\" numeric NOT NULL,\n\t\"unit\" \"enum_products_unit\" DEFAULT 'stuk',\n\t\"stock\" numeric DEFAULT 0,\n\t\"track_stock\" boolean DEFAULT false,\n\t\"active\" boolean DEFAULT true,\n\t\"supplier\" varchar,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"bread_items\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" varchar NOT NULL,\n\t\"description\" varchar,\n\t\"price\" numeric NOT NULL,\n\t\"image_id\" integer,\n\t\"category\" \"enum_bread_items_category\" DEFAULT 'broodje' NOT NULL,\n\t\"order\" numeric DEFAULT 100,\n\t\"active\" boolean DEFAULT true,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"bookings\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"reference\" varchar NOT NULL,\n\t\"guest_name\" varchar NOT NULL,\n\t\"guest_last_name\" varchar NOT NULL,\n\t\"email\" varchar,\n\t\"phone\" varchar,\n\t\"campsite_number\" varchar,\n\t\"arrival\" timestamp(3) with time zone NOT NULL,\n\t\"departure\" timestamp(3) with time zone NOT NULL,\n\t\"guests\" numeric DEFAULT 2,\n\t\"status\" \"enum_bookings_status\" DEFAULT 'active',\n\t\"external_source\" \"enum_bookings_external_source\" DEFAULT 'manual',\n\t\"notes\" varchar,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"orders_shop_items\" (\n\t\"_order\" integer NOT NULL,\n\t\"_parent_id\" integer NOT NULL,\n\t\"id\" varchar PRIMARY KEY NOT NULL,\n\t\"product_id\" integer,\n\t\"quantity\" numeric DEFAULT 1,\n\t\"price_at_purchase\" numeric,\n\t\"name\" varchar\n);\n",
  "CREATE TABLE \"orders_bread_items\" (\n\t\"_order\" integer NOT NULL,\n\t\"_parent_id\" integer NOT NULL,\n\t\"id\" varchar PRIMARY KEY NOT NULL,\n\t\"item_id\" integer,\n\t\"quantity\" numeric DEFAULT 1,\n\t\"price_at_purchase\" numeric,\n\t\"name\" varchar\n);\n",
  "CREATE TABLE \"orders\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"type\" \"enum_orders_type\" NOT NULL,\n\t\"guest_type\" \"enum_orders_guest_type\" NOT NULL,\n\t\"booking_id\" integer,\n\t\"delivery_date\" timestamp(3) with time zone,\n\t\"total\" numeric NOT NULL,\n\t\"payment_method\" \"enum_orders_payment_method\" DEFAULT 'mollie',\n\t\"payment_status\" \"enum_orders_payment_status\" DEFAULT 'open',\n\t\"mollie_payment_id\" varchar,\n\t\"mollie_payment_url\" varchar,\n\t\"guest_email\" varchar,\n\t\"guest_note\" varchar,\n\t\"fulfilled\" boolean DEFAULT false,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"payload_kv\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"key\" varchar NOT NULL,\n\t\"data\" jsonb NOT NULL\n);\n",
  "CREATE TABLE \"payload_locked_documents\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"global_slug\" varchar,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"payload_locked_documents_rels\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"order\" integer,\n\t\"parent_id\" integer NOT NULL,\n\t\"path\" varchar NOT NULL,\n\t\"users_id\" integer,\n\t\"media_id\" integer,\n\t\"product_categories_id\" integer,\n\t\"products_id\" integer,\n\t\"bread_items_id\" integer,\n\t\"bookings_id\" integer,\n\t\"orders_id\" integer\n);\n",
  "CREATE TABLE \"payload_preferences\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"key\" varchar,\n\t\"value\" jsonb,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "CREATE TABLE \"payload_preferences_rels\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"order\" integer,\n\t\"parent_id\" integer NOT NULL,\n\t\"path\" varchar NOT NULL,\n\t\"users_id\" integer\n);\n",
  "CREATE TABLE \"payload_migrations\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" varchar,\n\t\"batch\" numeric,\n\t\"updated_at\" timestamp(3) with time zone DEFAULT now() NOT NULL,\n\t\"created_at\" timestamp(3) with time zone DEFAULT now() NOT NULL\n);\n",
  "ALTER TABLE \"users_sessions\" ADD CONSTRAINT \"users_sessions_parent_id_fk\" FOREIGN KEY (\"_parent_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"product_categories\" ADD CONSTRAINT \"product_categories_image_id_media_id_fk\" FOREIGN KEY (\"image_id\") REFERENCES \"public\".\"media\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"products\" ADD CONSTRAINT \"products_category_id_product_categories_id_fk\" FOREIGN KEY (\"category_id\") REFERENCES \"public\".\"product_categories\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"products\" ADD CONSTRAINT \"products_image_id_media_id_fk\" FOREIGN KEY (\"image_id\") REFERENCES \"public\".\"media\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"bread_items\" ADD CONSTRAINT \"bread_items_image_id_media_id_fk\" FOREIGN KEY (\"image_id\") REFERENCES \"public\".\"media\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"orders_shop_items\" ADD CONSTRAINT \"orders_shop_items_product_id_products_id_fk\" FOREIGN KEY (\"product_id\") REFERENCES \"public\".\"products\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"orders_shop_items\" ADD CONSTRAINT \"orders_shop_items_parent_id_fk\" FOREIGN KEY (\"_parent_id\") REFERENCES \"public\".\"orders\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"orders_bread_items\" ADD CONSTRAINT \"orders_bread_items_item_id_bread_items_id_fk\" FOREIGN KEY (\"item_id\") REFERENCES \"public\".\"bread_items\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"orders_bread_items\" ADD CONSTRAINT \"orders_bread_items_parent_id_fk\" FOREIGN KEY (\"_parent_id\") REFERENCES \"public\".\"orders\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"orders\" ADD CONSTRAINT \"orders_booking_id_bookings_id_fk\" FOREIGN KEY (\"booking_id\") REFERENCES \"public\".\"bookings\"(\"id\") ON DELETE set null ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_parent_fk\" FOREIGN KEY (\"parent_id\") REFERENCES \"public\".\"payload_locked_documents\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_users_fk\" FOREIGN KEY (\"users_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_media_fk\" FOREIGN KEY (\"media_id\") REFERENCES \"public\".\"media\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_product_categories_fk\" FOREIGN KEY (\"product_categories_id\") REFERENCES \"public\".\"product_categories\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_products_fk\" FOREIGN KEY (\"products_id\") REFERENCES \"public\".\"products\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_bread_items_fk\" FOREIGN KEY (\"bread_items_id\") REFERENCES \"public\".\"bread_items\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_bookings_fk\" FOREIGN KEY (\"bookings_id\") REFERENCES \"public\".\"bookings\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_locked_documents_rels\" ADD CONSTRAINT \"payload_locked_documents_rels_orders_fk\" FOREIGN KEY (\"orders_id\") REFERENCES \"public\".\"orders\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_preferences_rels\" ADD CONSTRAINT \"payload_preferences_rels_parent_fk\" FOREIGN KEY (\"parent_id\") REFERENCES \"public\".\"payload_preferences\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "ALTER TABLE \"payload_preferences_rels\" ADD CONSTRAINT \"payload_preferences_rels_users_fk\" FOREIGN KEY (\"users_id\") REFERENCES \"public\".\"users\"(\"id\") ON DELETE cascade ON UPDATE no action;",
  "CREATE INDEX \"users_sessions_order_idx\" ON \"users_sessions\" USING btree (\"_order\");",
  "CREATE INDEX \"users_sessions_parent_id_idx\" ON \"users_sessions\" USING btree (\"_parent_id\");",
  "CREATE INDEX \"users_updated_at_idx\" ON \"users\" USING btree (\"updated_at\");",
  "CREATE INDEX \"users_created_at_idx\" ON \"users\" USING btree (\"created_at\");",
  "CREATE UNIQUE INDEX \"users_email_idx\" ON \"users\" USING btree (\"email\");",
  "CREATE INDEX \"media_updated_at_idx\" ON \"media\" USING btree (\"updated_at\");",
  "CREATE INDEX \"media_created_at_idx\" ON \"media\" USING btree (\"created_at\");",
  "CREATE UNIQUE INDEX \"media_filename_idx\" ON \"media\" USING btree (\"filename\");",
  "CREATE INDEX \"media_sizes_thumbnail_sizes_thumbnail_filename_idx\" ON \"media\" USING btree (\"sizes_thumbnail_filename\");",
  "CREATE INDEX \"media_sizes_card_sizes_card_filename_idx\" ON \"media\" USING btree (\"sizes_card_filename\");",
  "CREATE INDEX \"media_sizes_hero_sizes_hero_filename_idx\" ON \"media\" USING btree (\"sizes_hero_filename\");",
  "CREATE UNIQUE INDEX \"product_categories_slug_idx\" ON \"product_categories\" USING btree (\"slug\");",
  "CREATE INDEX \"product_categories_image_idx\" ON \"product_categories\" USING btree (\"image_id\");",
  "CREATE INDEX \"product_categories_updated_at_idx\" ON \"product_categories\" USING btree (\"updated_at\");",
  "CREATE INDEX \"product_categories_created_at_idx\" ON \"product_categories\" USING btree (\"created_at\");",
  "CREATE UNIQUE INDEX \"products_slug_idx\" ON \"products\" USING btree (\"slug\");",
  "CREATE INDEX \"products_category_idx\" ON \"products\" USING btree (\"category_id\");",
  "CREATE INDEX \"products_image_idx\" ON \"products\" USING btree (\"image_id\");",
  "CREATE INDEX \"products_updated_at_idx\" ON \"products\" USING btree (\"updated_at\");",
  "CREATE INDEX \"products_created_at_idx\" ON \"products\" USING btree (\"created_at\");",
  "CREATE INDEX \"bread_items_image_idx\" ON \"bread_items\" USING btree (\"image_id\");",
  "CREATE INDEX \"bread_items_updated_at_idx\" ON \"bread_items\" USING btree (\"updated_at\");",
  "CREATE INDEX \"bread_items_created_at_idx\" ON \"bread_items\" USING btree (\"created_at\");",
  "CREATE UNIQUE INDEX \"bookings_reference_idx\" ON \"bookings\" USING btree (\"reference\");",
  "CREATE INDEX \"bookings_updated_at_idx\" ON \"bookings\" USING btree (\"updated_at\");",
  "CREATE INDEX \"bookings_created_at_idx\" ON \"bookings\" USING btree (\"created_at\");",
  "CREATE INDEX \"orders_shop_items_order_idx\" ON \"orders_shop_items\" USING btree (\"_order\");",
  "CREATE INDEX \"orders_shop_items_parent_id_idx\" ON \"orders_shop_items\" USING btree (\"_parent_id\");",
  "CREATE INDEX \"orders_shop_items_product_idx\" ON \"orders_shop_items\" USING btree (\"product_id\");",
  "CREATE INDEX \"orders_bread_items_order_idx\" ON \"orders_bread_items\" USING btree (\"_order\");",
  "CREATE INDEX \"orders_bread_items_parent_id_idx\" ON \"orders_bread_items\" USING btree (\"_parent_id\");",
  "CREATE INDEX \"orders_bread_items_item_idx\" ON \"orders_bread_items\" USING btree (\"item_id\");",
  "CREATE INDEX \"orders_booking_idx\" ON \"orders\" USING btree (\"booking_id\");",
  "CREATE INDEX \"orders_updated_at_idx\" ON \"orders\" USING btree (\"updated_at\");",
  "CREATE INDEX \"orders_created_at_idx\" ON \"orders\" USING btree (\"created_at\");",
  "CREATE UNIQUE INDEX \"payload_kv_key_idx\" ON \"payload_kv\" USING btree (\"key\");",
  "CREATE INDEX \"payload_locked_documents_global_slug_idx\" ON \"payload_locked_documents\" USING btree (\"global_slug\");",
  "CREATE INDEX \"payload_locked_documents_updated_at_idx\" ON \"payload_locked_documents\" USING btree (\"updated_at\");",
  "CREATE INDEX \"payload_locked_documents_created_at_idx\" ON \"payload_locked_documents\" USING btree (\"created_at\");",
  "CREATE INDEX \"payload_locked_documents_rels_order_idx\" ON \"payload_locked_documents_rels\" USING btree (\"order\");",
  "CREATE INDEX \"payload_locked_documents_rels_parent_idx\" ON \"payload_locked_documents_rels\" USING btree (\"parent_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_path_idx\" ON \"payload_locked_documents_rels\" USING btree (\"path\");",
  "CREATE INDEX \"payload_locked_documents_rels_users_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"users_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_media_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"media_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_product_categories_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"product_categories_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_products_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"products_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_bread_items_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"bread_items_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_bookings_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"bookings_id\");",
  "CREATE INDEX \"payload_locked_documents_rels_orders_id_idx\" ON \"payload_locked_documents_rels\" USING btree (\"orders_id\");",
  "CREATE INDEX \"payload_preferences_key_idx\" ON \"payload_preferences\" USING btree (\"key\");",
  "CREATE INDEX \"payload_preferences_updated_at_idx\" ON \"payload_preferences\" USING btree (\"updated_at\");",
  "CREATE INDEX \"payload_preferences_created_at_idx\" ON \"payload_preferences\" USING btree (\"created_at\");",
  "CREATE INDEX \"payload_preferences_rels_order_idx\" ON \"payload_preferences_rels\" USING btree (\"order\");",
  "CREATE INDEX \"payload_preferences_rels_parent_idx\" ON \"payload_preferences_rels\" USING btree (\"parent_id\");",
  "CREATE INDEX \"payload_preferences_rels_path_idx\" ON \"payload_preferences_rels\" USING btree (\"path\");",
  "CREATE INDEX \"payload_preferences_rels_users_id_idx\" ON \"payload_preferences_rels\" USING btree (\"users_id\");",
  "CREATE INDEX \"payload_migrations_updated_at_idx\" ON \"payload_migrations\" USING btree (\"updated_at\");",
  "CREATE INDEX \"payload_migrations_created_at_idx\" ON \"payload_migrations\" USING btree (\"created_at\");"
];
